language: r

r: bioc-devel
warnings_are_errors: false
sudo: false
cache: packages

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

r_packages:
  - bookdown
  - tufte

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: XHhGVMEFs4bAz0/ShswkQv5rXffZhLwHbPDlMA8h6pF1VOOSSz0zZblrqhyCZbF5OpsYotQZpLlGsxsVbVqTVQsuK3IVf5HWIK9HuloP091eHNVkQ46+lH6q8gT6tuWMZMrGoalrTVtlUKfAk11E2k6cYLiSdCH/22OBv58TG1w=

env:
  global:
    - _R_CHECK_TIMINGS_="0"

